name: fe-monorepo

services:
  pgvector_db:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    environment:
      POSTGRES_DB: pgvector_db
      POSTGRES_USER: pgvector_db
      POSTGRES_PASSWORD: pgvector_db
    # DATABASE_URL === postgres://pgvector_db:pgvector_db@db:5432/pgvector_db
    ports:
      - "5432:5432"
    volumes:
      - pgvector_db_data:/var/lib/postgresql/data
      - ./pgvector.sql:/docker-entrypoint-initdb.d/pgvector.sql # init pgvector extension
    restart: always

  otel-lgtm:
    image: docker.io/grafana/otel-lgtm:latest
    ports:
      - "3111:3000" # Grafana UI
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    volumes:
      - ./otel-lgtm/grafana:/data/grafana
      - ./otel-lgtm/prometheus:/data/prometheus
      - ./otel-lgtm/loki:/data/loki
    environment:
      - GF_PATHS_DATA=/data/grafana
    env_file:
      - ./.env
    # stdin_open: true
    # tty: true

volumes:
  pgvector_db_data: